# markdown_export.py

import os
from datetime import datetime
from pathlib import Path
from typing import List, Optional
from schema import DialogueItem

def create_markdown_content(
    dialogue_items: List[DialogueItem],
    guest_name: str,
    focus_area: Optional[str] = None,
    source_info: str = "Generated content",
    generation_method: str = "Single-stage"
) -> str:
    """
    Create formatted markdown content from dialogue items.
    """
    
    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Create header
    markdown_content = f"""# Extended Podcast Dialogue

**Guest:** {guest_name}  
**Generated:** {timestamp}  
**Method:** {generation_method}  
**Length:** {len(dialogue_items)} exchanges  
"""
    
    if focus_area and focus_area != "No Specific Focus":
        markdown_content += f"**Focus Area:** {focus_area}  \n"
    
    markdown_content += f"**Source:** {source_info}  \n\n"
    
    # Add divider
    markdown_content += "---\n\n"
    
    # Add dialogue content
    markdown_content += "## Dialogue\n\n"
    
    for i, item in enumerate(dialogue_items, 1):
        # Format speaker name
        if item.speaker == "Host (Jane)":
            speaker_emoji = "🎙️"
            speaker_name = "**Host (Jane)**"
        else:
            speaker_emoji = "🎓"
            speaker_name = f"**{guest_name}**"
        
        # Add exchange number and content
        markdown_content += f"### {i}. {speaker_emoji} {speaker_name}\n\n"
        markdown_content += f"{item.text}\n\n"
    
    # Add footer with statistics
    markdown_content += "---\n\n"
    markdown_content += "## Statistics\n\n"
    
    host_exchanges = len([item for item in dialogue_items if item.speaker == "Host (Jane)"])
    guest_exchanges = len([item for item in dialogue_items if item.speaker == "Guest"])
    total_words = sum(len(item.text.split()) for item in dialogue_items)
    avg_words_per_exchange = total_words / len(dialogue_items) if dialogue_items else 0
    
    markdown_content += f"- **Total Exchanges:** {len(dialogue_items)}\n"
    markdown_content += f"- **Host Exchanges:** {host_exchanges}\n"
    markdown_content += f"- **Guest Exchanges:** {guest_exchanges}\n"
    markdown_content += f"- **Total Words:** {total_words:,}\n"
    markdown_content += f"- **Average Words per Exchange:** {avg_words_per_exchange:.1f}\n"
    markdown_content += f"- **Estimated Reading Time:** {total_words // 200:.1f} minutes\n\n"
    
    markdown_content += "*Generated by Open NotebookLM Extended Dialogue System*\n"
    
    return markdown_content

def save_extended_dialogue_markdown(
    dialogue_items: List[DialogueItem],
    guest_name: str,
    focus_area: Optional[str] = None,
    source_info: str = "Generated content",
    generation_method: str = "Single-stage",
    output_dir: str = "extended_dialogues"
) -> str:
    """
    Save extended dialogue as markdown file and return the file path.
    """
    
    # Create output directory if it doesn't exist
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)
    
    # Generate filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    guest_clean = "".join(c for c in guest_name if c.isalnum() or c in (' ', '-', '_')).strip()
    guest_clean = guest_clean.replace(' ', '_')
    
    focus_suffix = ""
    if focus_area and focus_area != "No Specific Focus":
        focus_clean = "".join(c for c in focus_area if c.isalnum() or c in (' ', '-', '_')).strip()
        focus_clean = focus_clean.replace(' ', '_')
        focus_suffix = f"_{focus_clean}"
    
    filename = f"extended_dialogue_{timestamp}_{guest_clean}{focus_suffix}.md"
    file_path = output_path / filename
    
    # Generate markdown content
    markdown_content = create_markdown_content(
        dialogue_items=dialogue_items,
        guest_name=guest_name,
        focus_area=focus_area,
        source_info=source_info,
        generation_method=generation_method
    )
    
    # Write to file
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        
        print(f"📝 Extended dialogue saved: {file_path}")
        return str(file_path)
        
    except Exception as e:
        print(f"❌ Failed to save markdown file: {e}")
        return None

def get_generation_method_info(scratchpad: str) -> tuple[str, str]:
    """
    Extract generation method and source info from scratchpad.
    """
    
    generation_method = "Single-stage"
    source_info = "Generated content"
    
    if "Stage 1:" in scratchpad and "Stage 2:" in scratchpad:
        generation_method = "Multi-stage (3 stages)"
        
        # Count stages
        stage_count = scratchpad.count("Stage ")
        if stage_count > 0:
            generation_method = f"Multi-stage ({stage_count} stages)"
    
    # Extract focus area info if present
    if "Focus:" in scratchpad:
        focus_part = scratchpad.split("Focus:")[-1].strip()
        if focus_part:
            source_info = f"Generated content (Focus: {focus_part})"
    
    return generation_method, source_info